= Lab: Deploying RHEL AI instance on AWS using the CLI

In this lab exercise, deployment the RHEL AI cloud instance using the RHEL AI AMI built in previous lab.

* Populate environment variables for when you create the instance
+
[subs="+quotes,+macros"]
----
$ instance_name=rhel-ai-instance
$ ami=<ami-id>
$ instance_type=<instance-type-size>
$ key_name=<key-pair-name>
$ security_group=<sg-id>
$ disk_size=<size-of-disk>
$ subnet=<subnet-id>
----

. For various parameters, you need to gather the ID of the variable.
.. To access the image ID, run the following command:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# aws ec2 describe-images --owners self
----

.. To access the security group ID, run the following command:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# aws ec2 describe-security-groups
----

.. To access the subnet ID, run the following command:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# aws ec2 describe-subnets
----

... Example:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# instance_name=rhel-ai-instance
[root@ip-172-17-1-180 ~]# ami=ami-0fb016f0818c18903
[root@ip-172-17-1-180 ~]# instance_type=g6.xlarge
[root@ip-172-17-1-180 ~]# key_name=rhel9
[root@ip-172-17-1-180 ~]# security_group=sg-075b15dc567c48d67
[root@ip-172-17-1-180 ~]# disk_size=200
[root@ip-172-17-1-180 ~]# subnet=subnet-085a32c2ad7d2b8c3
----

* Create RHEL AI instance using the variables by running the following command:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# aws ec2 run-instances \
    --image-id $ami \
    --instance-type $instance_type \
    --key-name $key_name \
    --security-group-ids $security_group \
    --subnet-id $subnet \
    --block-device-mappings DeviceName=/dev/sda1,Ebs='{VolumeSize='$disk_size'}' \
    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value='$instance_name'}]'
----

* The default user account in the RHEL AI AMI is _cloud-user_. It has all permissions via sudo without password.

* Take passwordless ssh of the instance using the public IP address and verify that your Red Hat Enterprise Linux AI tools are installed correctly. 
. You need to run the ilab command:
+
[subs="+quotes,+macros"]
----
$ ssh -i ~/Downloads/rhel9.pem cloud-user@3.147.72.110
[cloud-user@ip-172-17-1-181 ~] $ ilab
Example output
$ ilab
Usage: ilab [OPTIONS] COMMAND [ARGS]...
----

* Congratulations! You have successfully deployed RHEL AI instance on AWS using customized RHEL AI AMI.