= Lab: Deploying RHEL AI instance on AWS using the CLI

In this lab exercise, deployment of the RHEL AI cloud instance using the RHEL AI AMI built in the previous lab.

* Populate environment variables for when you create the instance.
+
[subs="+quotes,+macros"]
----
$ instance_name=rhel-ai-instance
$ ami=<ami-id>
$ instance_type=<instance-type-size>
$ key_name=<key-pair-name>
$ security_group=<sg-id>
$ disk_size=<size-of-disk>
$ subnet=<subnet-id>
----

. For various parameters, you need to gather the ID of the variable.
.. To access the image ID, run the following command:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# aws ec2 describe-images --owners self
----

.. To access the security group ID, run the following command:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# aws ec2 describe-security-groups
----

.. To access the subnet ID, run the following command:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# aws ec2 describe-subnets
----

... Example:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# instance_name=rhel-ai-instance
[root@ip-172-17-1-180 ~]# ami=ami-0fb016f0818c18903
[root@ip-172-17-1-180 ~]# instance_type=g6.xlarge
[root@ip-172-17-1-180 ~]# key_name=rhel9
[root@ip-172-17-1-180 ~]# security_group=sg-075b15dc567c48d67
[root@ip-172-17-1-180 ~]# disk_size=200
[root@ip-172-17-1-180 ~]# subnet=subnet-085a32c2ad7d2b8c3
----

* Create RHEL AI instance using the variables by running the following command:
+
[subs="+quotes,+macros"]
----
[root@ip-172-17-1-180 ~]# aws ec2 run-instances \
    --image-id $ami \
    --instance-type $instance_type \
    --key-name $key_name \
    --security-group-ids $security_group \
    --subnet-id $subnet \
    --block-device-mappings DeviceName=/dev/sda1,Ebs='{VolumeSize='$disk_size'}' \
    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value='$instance_name'}]'
----

* The default user account in the RHEL AI AMI is _cloud-user_. It has all permissions via sudo without a password.

* Take passwordless ssh of the instance using the public IP address and verify that your Red Hat Enterprise Linux AI tools are installed correctly. 
. You need to run the ilab command and notice the error.
+
[subs="+quotes,+macros"]
----
$ ssh -i ~/Downloads/rhel9.pem cloud-user@3.147.72.110
[cloud-user@ip-172-17-1-31 ~]$ ilab
This host is not connected to Red Hat Insights.

To connect this host to Red Hat Insights run the following command:
sudo rhc connect --organization <org_id> --activation-key <your_activation_key>

To generate an Activation Key:
https://console.redhat.com/insights/connector/activation-keys (this page will also display your Organization ID).

For more information on Red Hat Insights, please visit:
https://docs.redhat.com/en/documentation/subscription_central/1-latest/html/getting_started_with_activation_keys_on_the_hybrid_cloud_console/assembly-creating-managing-activation-keys
----

* Resolve the error using your organization ID and activation key to register the system to the Red Hat Insights.
+
[subs="+quotes,+macros"]
----
[cloud-user@ip-172-17-1-31 ~]$ sudo rhc connect --organization <your-organisation-id> --activation-key <your-activation-key>
Connecting ip-172-17-1-31.us-east-2.compute.internal to Red Hat.
This might take a few seconds.

● Connected to Red Hat Subscription Management
● Connected to Red Hat Insights
● Activated the Remote Host Configuration daemon
● Enabled console.redhat.com services: remote configuration, insights, remediations, compliance

Successfully connected to Red Hat!

Manage your connected systems: https://red.ht/connector
----

* Execute the ilab command and notice the InstructLab is executing successfully.
+
[subs="+quotes,+macros"]
----
[cloud-user@ip-172-17-1-31 ~]$ ilab
Usage: ilab [OPTIONS] COMMAND [ARGS]...

  CLI for interacting with InstructLab.

  If this is your first time running ilab, it's best to start with `ilab
  config init` to create the environment.
----

* Congratulations! You have successfully deployed the RHEL AI instance on AWS with built-in InstructLab using customized RHEL AI AMI.